show more context for errors from fluxctl
Errors in fluxctl are unwrapped before printing since we want to
format flux-specific errors specially, and they can come wrapped.

However, the unwrapping can lead to losing context when printing
non-flux-specific errors.

For instance, after
https://github.com/justinbarrick/go-k8s-portforward/pulls/3 we display
the following when a kubeconfig file isn't found:

Error: invalid configuration: no configuration has been provided
Run 'fluxctl identity --help' for usage.

Which is the cause of a much more helpful error when in full:

Error: Could not load kubernetes configuration file: invalid configuration: no configuration has been provided
Run 'fluxctl identity --help' for usage.

This change removes the unwrapping for non-flux-specific errors.